@startuml
class node<< (I, #FF7700) Identity>> {
  - port_id: string
}

class physical_interface<< (I, #FF7700) Identity>> {
}

class physical_router<< (I, #FF7700) Identity>> {
}

class fabric<< (I, #FF7700) Identity>> {
}

class fabric_namespace<< (I, #FF7700) Identity>> {
}

fabric --> physical_router
fabric --> node
physical_router --> physical_interface
fabric -> fabric_namespace
node <-- physical_interface

@enduml