@startuml

skinparam object {
	BackgroundColor PaleGreen
	BackgroundColor<<PhysicalRouter>> Wheat
	BackgroundColor<<PhysicalInterface>> Wheat
	BackgroundColor<<LogicalRouter>> Wheat
	BackgroundColor<<VirtualNetwork>> Wheat
	BackgroundColor<<VirtualMachineInterface>> Wheat
}

package default-domain {
    object Firewall_Svc<<ServiceTemplate>> {
        - properties:
            \tservice_type: "firewall"
            \tinterface_types: ["left", "right"]
            \tservice_virtualization_type: "physical_device"
    }
}

package global_system_config {

    object SRX<<PhysicalRouter>> {
        rb_roles:
        \tPNF-ServiceChain@pnf
    }

    object SRX_Left_PI<<PhysicalInterface>> {
    }

    object SRX_Right_PI<<PhysicalInterface>> {
    }

    object PNF_Cluster<<ServiceApplianceSet>> {
    }

    object PNF<<ServiceAppliance>> {
    }

    object QFX<<PhysicalRouter>> {
        rb_roles:
            \tCRB-MCAST-Gateway@leaf
            \tPNF-ServiceChain@leaf
    }

    object QFX_Left_PI<<PhysicalInterface>> {
    }

    object QFX_Right_PI<<PhysicalInterface>> {
    }

    SRX *-- SRX_Left_PI: has
    SRX *-- SRX_Right_PI: has

    QFX *-- QFX_Left_PI: has
    QFX *-- QFX_Right_PI: has

    QFX_Left_PI <---> SRX_Left_PI: underlay conn
    QFX_Right_PI <---> SRX_Right_PI: underlay conn


    PNF_Cluster *- PNF: has
    SRX_Left_PI <-- PNF: "left\t\t\nunderlay\t\t\nport\t\t"
    SRX_Right_PI <-- PNF: right\nunderlay\nport
}

package tenant_project {
    object FW_Svc_inst<<ServiceInstance>> {

    }

    object Engineering_LR<<LogicalRouter>> {
    }

    object Sales_LR<<LogicalRouter>> {
    }

    object Dev<<VirtualNetwork>> {
    }

    object QA<<VirtualNetwork>> {
    }

    object Pre_Sales<<VirtualNetwork>> {
    }

    object Post_Sales<<VirtualNetwork>> {
    }

    object Engineering_LR_Internal_VN<<VirtualNetwork>> {
    }

    object Sales_LR_Internal_VN<<VirtualNetwork>> {
    }

    object Left_Attachment_Point<<PortTuple>> {
    }

    object Right_Attachment_Point<<PortTuple>> {
    }

    object VMI_1<<VirtualMachineInterface>> {
    }

    object VMI_2<<VirtualMachineInterface>> {
    }

    object VMI_3<<VirtualMachineInterface>> {
    }

    object VMI_4<<VirtualMachineInterface>> {
    }

    Dev <-- VMI_1
    QA <-- VMI_2
    Pre_Sales <-- VMI_3
    Post_Sales <-- VMI_4

    Engineering_LR <-- Dev
    Engineering_LR <-- QA
    Engineering_LR --> Engineering_LR_Internal_VN

    Sales_LR <-- Pre_Sales
    Sales_LR <-- Post_Sales
    Sales_LR --> Sales_LR_Internal_VN

    FW_Svc_inst --> Left_Attachment_Point: Left
    FW_Svc_inst --> Right_Attachment_Point: Right

    Left_Attachment_Point --> Engineering_LR
    Right_Attachment_Point --> Sales_LR
}

PNF_Cluster <-- Firewall_Svc
Firewall_Svc <-- FW_Svc_inst
QFX <-- Engineering_LR: extend left tenant\nVRF to border leaf
QFX <-- Sales_LR: extend right tenant\nVRF to border leaf
QFX_Left_PI <-- Left_Attachment_Point: left underlay port
QFX_Right_PI <-- Right_Attachment_Point: right underlay port

'hide PNF
'hide PNF_Cluster
'hide Firewall_Svc
hide FW_Svc_inst
hide Left_Attachment_Point
hide Right_Attachment_Point

'hide Dev
'hide QA
'hide Pre_Sales
'hide Post_Sales
'hide Engineering_LR
'hide Sales_LR
'hide VMI_1
'hide VMI_2
'hide VMI_3
'hide VMI_4
'hide Sales_LR_Internal_VN
'hide Engineering_LR_Internal_VN

@enduml