@startuml
package global-system-config {
  class physical_router << (I, #FF7700) Identity>> {
  }

  class physical_interface << (I, #FF7700) Identity>> {
  }

  class logical_interface << (I, #FF7700) Identity>> {
  }

  class node << (I, #FF7700) Identity>> #lightgreen {
    - role_assignments: List<role_assignment>[
        { role: string,
          port-networks: List<port_network>[{
              port: string,
              networks: List<string>,
              members: List<string>
          }]
        }]
  }

  class port << (I, #FF7700) Identity>> #lightgreen {
  }

  class port_group << (I, #FF7700) Identity>> #lightgreen {
  }

  physical_router *-- physical_interface
  physical_interface *-- "logical_interface"

  node *-- port
  node *-- "port_group"
  "port" <- "port_group": contains

  physical_interface -> "port": \nlldp discovered\nphysical connection
}

package project {
  class virtual_network << (I, #FF7700) Identity>> {
  }

  class network_ipam << (I, #FF7700) Identity>> {
    - subnets: List<IpamSubnetType> [
        - subnet prefix
        - gateway
        - <b>vlan-tag
        - <b>dhcp-relay-server
      ]
  }

  virtual_network --> network_ipam
}
@enduml